# Generated by Django 6.0.4 on 2026-05-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_order_promo_code'),
        ('users', '0002_specialization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='service_types',
            field=models.ManyToManyField(related_name='specializations', to='cleaning.servicetype'),
        ),
    ]
