# Generated by Django 6.0.4 on 2026-09-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_banner_partner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
